site_name: depthcharge
repo_url: https://github.com/wfondrie/depthcharge
nav:
  - Getting Started: 'index.md'
  - Building Blocks:
    - 'building-blocks/index.md'
    - Model Components: 'building-blocks/components.md'
    - Data Components: 'building-blocks/data.md'
    - Building a Model: 'building-blocks/new-model.md'
  - End-to-End Models: 'models.md'

theme:
  name: material
  font:
    text: Roboto

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: true
            heading_level: 3
            docstring_section_style: spacy
            show_source: false
            merge_init_into_class: true

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wfondrie
